//
// **** AUTOMATICALLY GENERATED BY mk-node-decls.pl -- DO NOT EDIT ****
//
#include <cdk/ast/all.h>

#ifdef __NODE_DECLARATIONS_ONLY__

namespace og {
class evaluation_node; 
class for_node; 
class function_declaration_node; 
class if_else_node; 
class if_node; 
class print_node; 
class program_node; 
class read_node; 
class visitor_decls; 
class while_node; 

} // namespace og

#else /* !defined(__NODE_DECLARATIONS_ONLY__) */

#ifndef __AUTOMATIC_og_NODE_ALLNODES_H__
#define __AUTOMATIC_og_NODE_ALLNODES_H__

#include "ast/evaluation_node.h"
#include "ast/for_node.h"
#include "ast/function_declaration_node.h"
#include "ast/if_else_node.h"
#include "ast/if_node.h"
#include "ast/print_node.h"
#include "ast/program_node.h"
#include "ast/read_node.h"
#include "ast/visitor_decls.h"
#include "ast/while_node.h"


#endif /* !defined(__AUTOMATIC_og_NODE_ALLNODES_H__) */

#endif /* !defined(__NODE_DECLARATIONS_ONLY__) */
